### ISSUE TITLE
Creating a workspace package?

### ISSUE THREAD

**Issue by BriBecker** [SendSafely/Python-Client-API#2]
It doesn't appear the python api supports creating a workspace version of a package? I see the Package init method doesn't appear to allow for a simple way to set vdr parameter to be True as appears in this documentation: https://bump.sh/doc/sendsafely-rest-api#operation-put-package

**Comment by BriBecker** [comment]
Actually I think I jumped the gun. Looks like I can just create a workspace through the UI and regularly deliver data there through the API. I don't really need to create fresh new workspaces through the API. Thanks!

**Comment by SendSafely-GitHub** [comment]
Hi Brian -- Thank you for reporting this. We plan on releasing a function for creating workspace packages in our next python release. For now we are glad to hear that you identified a workaround.
